# Generated by Django 2.2.1 on 2020-01-14 01:13

from django.db import migrations, models
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=models.FileField(upload_to='media/static/images/', validators=[home.validators.validate_file_extension]),
        ),
    ]
