# Generated by Django 2.2.1 on 2020-01-14 01:15

from django.db import migrations, models
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200114_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=models.FileField(upload_to='C:/Users/akanksha kulkarni/DjangoProjects/Christmas/media/', validators=[home.validators.validate_file_extension]),
        ),
    ]
