# Generated by Django 2.2.1 on 2020-01-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
