# Generated by Django 2.2.1 on 2020-01-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200114_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
